### ISSUE TITLE
The key argument of `Registry.get` must be a str

### ISSUE THREAD

**Issue by MargeryLab** [HarborYuan/ovsam#40]
when i run the inference command, there is a error, how can i solve it?

Traceback (most recent call last):
  File "/maggie.meng/code/ovsam/tools/test.py", line 177, in <module>
    main()
  File "/maggie.meng/code/ovsam/tools/test.py", line 141, in main
    runner = Runner.from_cfg(cfg)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/runner/runner.py", line 412, in __init__
    self.model = self.build_model(model)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/runner/runner.py", line 819, in build_model
Traceback (most recent call last):
  File "/maggie.meng/code/ovsam/tools/test.py", line 177, in <module>
    model = MODELS.build(model)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    main()
  File "/maggie.meng/code/ovsam/tools/test.py", line 141, in main
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    runner = Runner.from_cfg(cfg)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/maggie.meng/code/ovsam/seg/models/detectors/ovsam.py", line 63, in __init__
    runner = cls(
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/runner/runner.py", line 412, in __init__
    self.neck = MODELS.build(neck)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    self.model = self.build_model(model)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/runner/runner.py", line 819, in build_model
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)    
model = MODELS.build(model)  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg

  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    obj = obj_cls(**args)  # type: ignore
  File "/maggie.meng/code/ovsam/seg/models/necks/transformer_neck.py", line 43, in __init__
    patch_embed = PatchEmbed(
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmdet/models/layers/transformer/utils.py", line 250, in __init__
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    self.projection = build_conv_layer(
    return build_from_cfg(cfg, registry, default_args)  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmcv/cnn/bricks/conv.py", line 43, in build_conv_layer

  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    conv_layer = registry.get(layer_type)    
obj = obj_cls(**args)  # type: ignore  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/registry.py", line 441, in get

  File "/maggie.meng/code/ovsam/seg/models/detectors/ovsam.py", line 63, in __init__
    self.neck = MODELS.build(neck)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    raise TypeError(
TypeError: The key argument of `Registry.get` must be a str, got <class 'type'>
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/maggie.meng/code/ovsam/seg/models/necks/transformer_neck.py", line 43, in __init__
    patch_embed = PatchEmbed(
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmdet/models/layers/transformer/utils.py", line 250, in __init__
    self.projection = build_conv_layer(
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmcv/cnn/bricks/conv.py", line 43, in build_conv_layer
    conv_layer = registry.get(layer_type)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/mmengine/registry/registry.py", line 441, in get
    raise TypeError(
TypeError: The key argument of `Registry.get` must be a str, got <class 'type'>
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 523118) of binary: /root/anaconda3/envs/ovsam_demo/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/ovsam_demo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/ovsam_demo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-27_16:34:49
  host      : 9rqdhjcat3fsm-0
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 523119)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-27_16:34:49
  host      : 9rqdhjcat3fsm-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 523118)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
